export const navMenus=[
    {
        name:'首页管理',
        order:1,
        children:[
            {
                name:"首页",
                path:'/',
                suborder:1
            }
        ]
    },
    {
        name:'机构管理',
        order:2,
        children:[
            {
                name:"机构信息",
                path:'/instInfo',
                suborder:2
            },
            {
                name:"机构费率",
                path:'/instPercent',
                suborder:3
            },
            {
                name:"机构审核",
                path:'/instCheck',
                suborder:4
            }
        ]
    },
    {
        name:'账户中心',
        order:3,
        children:[
            {
                name:"账户信息",
                path:'/accountInfo',
                suborder:5
            },
            {
                name:"账户充值历史",
                path:'/accountCharge',
                suborder:6
            },
            {
                name:"账户调账",
                path:'/accountCtrol',
                suborder:7
            },
            {
                name:"调账审核",
                path:'/accountCheck',
                suborder:8
            },
            {
                name:"日终余额查询",
                path:'/balance',
                suborder:9
            }
        ]
    },
    {
        name:'交易管理',
        order:4,
        children:[
            {
                name:"交易记录",
                path:'/dealRecord',
                suborder:10
            },
            {
                name:"交易对账",
                path:'/dealChecking',
                suborder:11
            },
            {
                name:"交易累计",
                path:'/dealSum',
                suborder:12
            },
            {
                name:"客户交易统计",
                path:'/dealCcount',
                suborder:13
            }
        ]
    },
    {
        name:'发票管理',
        order:5,
        children:[
            {
                name:"发票申请",
                path:'/billApply',
                suborder:14
            },
            {
                name:"邮寄地址",
                path:'/address',
                suborder:15
            },
            {
                name:"发票审核",
                path:'/billCheck',
                suborder:16
            }
        ]
    },
    {
        name:'风险管理',
        order:6,
        children:[
            {
                name:"资质业务核实",
                path:'/businessVerify',
                suborder:17
            },
            {
                name:"董监高灰名单",
                path:'/grayList',
                suborder:18
            },
            {
                name:"风控黑名单",
                path:'/blankList',
                suborder:19
            },
            {
                name:"交易限额风控",
                path:'/riskCtrol',
                suborder:20
            },
            {
                name:"调单管理",
                path:'/manager',
                suborder:21
            }
        ]
    }
]